logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    com.yutsuki.telegram.service: debug
jwt:
  private.key : classpath:app.key
  public.key : classpath:app.pub
telegram:
  url: https://api.telegram.org/bot%s/sendMessage
  chat-id: 959034845
  api-token: 6800120949:AAHeWsrkT38-SQHfoTLpkvEDk9KL-nDaY_8