spring:
  datasource:
    url: jdbc:mysql://103.99.11.176:3306/stock?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Su%dhQ&wYFx*V8K%
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  redis:
    host: 185.78.165.239
    port: 6379
    password: PlFRkuNRJ8xoIHF
jwt:
  private.key : classpath:app.key
  public.key : classpath:app.pub
  expire: 1h
  issuer: yutsuki
telegram:
  url: https://api.telegram.org/bot%s/sendMessage
  chat-id: 959034845
  api-token: 6800120949:AAHeWsrkT38-SQHfoTLpkvEDk9KL-nDaY_8
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    com.yutsuki.stock.service: debug
    org.hibernate.SQL: debug
server:
  port: 8083
